### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yuweijie021** [ChellyLau/MomentKit#1]
MMImageListView.m->setMoment->imageView用SDImage会导致内存爆增，闪退，这个怎么解决？例如：//[imageView sd_setImageWithURL:[NSURL URLWithString:moment.filePaths[i]] placeholderImage:[UIImage imageNamed:@"default.jpg"]];

**Comment by CheeryLau** [comment]
对于分辨率比较大的图片，是比较容易带来内存警告，可以用以下方法解决：
1、在receive memory warning方法中，清理缓存，SDImageCache 中有方法，自己查阅以下。
2、重写图片加载方法，对图片压缩，这个就需要你好好读SDWebImage的API，在首次加载图片，缓存之前就要压缩图片。

**Comment by zhujames-ios** [comment]
用这个方法将图片等比例缩放就好了。

//指定宽度按比例缩放
-(UIImage *) imageCompressForWidthScale:(UIImage *)sourceImage targetWidth:(CGFloat)defineWidth{
    
    UIImage *newImage = nil;
    CGSize imageSize = sourceImage.size;
    CGFloat width = imageSize.width;
    CGFloat height = imageSize.height;
    CGFloat targetWidth = defineWidth;
    CGFloat targetHeight = height / (width / targetWidth);
    CGSize size = CGSizeMake(targetWidth, targetHeight);
    CGFloat scaleFactor = 0.0;
    CGFloat scaledWidth = targetWidth;
    CGFloat scaledHeight = targetHeight;
    CGPoint thumbnailPoint = CGPointMake(0.0, 0.0);
    
    if(CGSizeEqualToSize(imageSize, size) == NO){
        
        CGFloat widthFactor = targetWidth / width;
        CGFloat heightFactor = targetHeight / height;
        
        if(widthFactor > heightFactor){
            scaleFactor = widthFactor;
        }
        else{
            scaleFactor = heightFactor;
        }
        scaledWidth = width * scaleFactor;
        scaledHeight = height * scaleFactor;
        
        if(widthFactor > heightFactor){
            
            thumbnailPoint.y = (targetHeight - scaledHeight) * 0.5;
            
        }else if(widthFactor < heightFactor){
            
            thumbnailPoint.x = (targetWidth - scaledWidth) * 0.5;
        }
    }
    
    UIGraphicsBeginImageContext(size);
    
    CGRect thumbnailRect = CGRectZero;
    thumbnailRect.origin = thumbnailPoint;
    thumbnailRect.size.width = scaledWidth;
    thumbnailRect.size.height = scaledHeight;
    
    [sourceImage drawInRect:thumbnailRect];
    
    newImage = UIGraphicsGetImageFromCurrentImageContext();
    
    if(newImage == nil){
        
        NSLog(@"scale image fail");
    }
    UIGraphicsEndImageContext();
    return newImage;
}
