### ISSUE TITLE
你的图片集合 怎么处理的

### ISSUE THREAD

**Issue by yy103zhu** [ChellyLau/MomentKit#11]
moment.pictureList 里的类型是字典嘛？ 后台要返回的直接输网络图片地址 我该怎么处理显示YYModel 直接转化 moment.pictureList 这个里面的数组是不对的

**Comment by ChellyLau** [comment]
hi.... moment.pictureList存放的是MPicture，我在类中有写。

// 图片集合
@property (nonatomic, strong) NSArray<MPicture *> *pictureList;

数组里放字符串、字典还是Model都是可以的，要看你的需求，如果你想使用YYModel也是可以，引入YYModel的头文件就可以使用了。

**Comment by ChellyLau** [comment]
> moment.pictureList 里的类型是字典嘛？ 后台要返回的直接输网络图片地址 我该怎么处理显示YYModel 直接转化 moment.pictureList 这个里面的数组是不对的

hi.... moment.pictureList存放的是MPicture，我在类中有写。

// 图片集合
@Property (nonatomic, strong) NSArray<MPicture *> *pictureList;

数组里放字符串、字典还是Model都是可以的，要看你的需求，如果你想使用YYModel也是可以，引入YYModel的头文件就可以使用了。
