### ISSUE TITLE
MK.db

### ISSUE THREAD

**Issue by mcyuan** [ChellyLau/MomentKit#12]
你好，请问能共享下MK.db吗，在DEMO里面没找到,感谢！！！

**Comment by ChellyLau** [comment]
用模拟器运行，打印document路径，使用“访达”，前往文件夹，输入document路径，就可以看到MK.db。

**Comment by ChellyLau** [comment]
> 你好，请问能共享下MK.db吗，在DEMO里面没找到,感谢！！！

用模拟器运行，打印document路径，使用“访达”，前往文件夹，输入document路径，就可以看到MK.db。
