### ISSUE TITLE
UUActionSheet

### ISSUE THREAD

**Issue by kes792** [ChellyLau/MomentKit#13]
Username for 'https://github.com/CheeryLau/UUActionSheet.git': 
Password for 'https://1625977078@qq.com@github.com/CheeryLau/UUActionSheet.git': 

fatal: Authentication failed for 'https://github.com/CheeryLau/UUActionSheet.git/'

**Comment by sushushu** [comment]
pod install的时候报错哦：

```
[!] Error installing UUActionSheet
[!] /usr/bin/git clone https://github.com/CheeryLau/UUActionSheet.git /var/folders/7q/416k793j4m183q7dgpg__38m0000gn/T/d20190328-15041-y0gr2c --template= --single-branch --depth 1 --branch 1.7

Cloning into '/var/folders/7q/416k793j4m183q7dgpg__38m0000gn/T/d20190328-15041-y0gr2c'...
remote: Repository not found.
fatal: repository 'https://github.com/CheeryLau/UUActionSheet.git/' not found
```

**Comment by ChellyLau** [comment]
再试一下，可以了。

**Comment by ChellyLau** [comment]
> Username for 'https://github.com/CheeryLau/UUActionSheet.git':
> Password for 'https://1625977078@qq.com@github.com/CheeryLau/UUActionSheet.git':
> 
> fatal: Authentication failed for 'https://github.com/CheeryLau/UUActionSheet.git/'

已修复。

**Comment by ChellyLau** [comment]
> pod install的时候报错哦：
> 
> ```
> [!] Error installing UUActionSheet
> [!] /usr/bin/git clone https://github.com/CheeryLau/UUActionSheet.git /var/folders/7q/416k793j4m183q7dgpg__38m0000gn/T/d20190328-15041-y0gr2c --template= --single-branch --depth 1 --branch 1.7
> 
> Cloning into '/var/folders/7q/416k793j4m183q7dgpg__38m0000gn/T/d20190328-15041-y0gr2c'...
> remote: Repository not found.
> fatal: repository 'https://github.com/CheeryLau/UUActionSheet.git/' not found
> ```

已修复。
