### ISSUE TITLE
请问您朋友圈预览图片的大小在哪个方法里设置的

### ISSUE THREAD

**Issue by slz759** [ChellyLau/MomentKit#14]
那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！

**Comment by slz759** [comment]
找到了，不好意思，原来我自己把宏定义改了。

**Comment by ChellyLau** [comment]
> 找到了，不好意思，原来我自己把宏定义改了。

**Comment by ChellyLau** [comment]
> 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！

sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。

**Comment by ChellyLau** [comment]
> 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！

sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。

**Comment by slz759** [comment]
> > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> 
> sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。

啊！谢谢关注到我的留言，其实确实还有一个问题。即IMageLIstView中第一个方法中的   imageView.tag = 1000 + i，这个代表了什么我其实不太明白诶。另外在导入pods后，Frameworks中的.a文件显示红色，我在网上查到好多方法试过了都没有作用。如果您方便的话可以解答一下吗？我这边因为刚刚开始学习，可能问题比较繁琐，谢谢您啦~

**Comment by slz759** [comment]
> > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> 
> sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。

额......其实还有，即我自己新创立了一个项目，就是在抄您的源码并且抄一句搜一句去理解。但是很奇怪的是，我无法像您这样，定义了一个宏定义文件之后导入pch文件就直接应用到全局。就是说，比如我在Model文件夹里定义的文件，不可以在另外的比如View文件夹里访问，导致我做什么都需要手动引入（手动引入时，自动补全也不会显示本文件夹之外的文件但是可以导入）。全局宏也用不了。

是不是因为我现在还没抄完，项目还无法编译，所以pch文件暂时起不到作用呢？

**Comment by ChellyLau** [comment]
> > > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> > 
> > 
> > sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。
> 
> 啊！谢谢关注到我的留言，其实确实还有一个问题。即IMageLIstView中第一个方法中的 imageView.tag = 1000 + i，这个代表了什么我其实不太明白诶。另外在导入pods后，Frameworks中的.a文件显示红色，我在网上查到好多方法试过了都没有作用。如果您方便的话可以解答一下吗？我这边因为刚刚开始学习，可能问题比较繁琐，谢谢您啦~

hi.....，libPods-MomentKit.a显示红色并不影响运行的。理论上执行完pod install，模拟器就可以运行成功，可以看到页面啦。如果没有运行成功，还得具体看报错信息。 imageView.tag = 1000 + i，就是设置tag，为了防止tag从0开始，因为[self viewWithTag:0]取得是self。

**Comment by ChellyLau** [comment]
> > > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> > 
> > 
> > sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。
> 
> 额......其实还有，即我自己新创立了一个项目，就是在抄您的源码并且抄一句搜一句去理解。但是很奇怪的是，我无法像您这样，定义了一个宏定义文件之后导入pch文件就直接应用到全局。就是说，比如我在Model文件夹里定义的文件，不可以在另外的比如View文件夹里访问，导致我做什么都需要手动引入（手动引入时，自动补全也不会显示本文件夹之外的文件但是可以导入）。全局宏也用不了。
> 
> 是不是因为我现在还没抄完，项目还无法编译，所以pch文件暂时起不到作用呢？


pch文件需要设置，才能起作用，具体见下图。

![image](https://user-images.githubusercontent.com/25630724/56257008-7a846480-60fd-11e9-894c-35ca6bce316a.png)

**Comment by slz759** [comment]
> > > > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> > > 
> > > 
> > > sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。
> > 
> > 
> > 啊！谢谢关注到我的留言，其实确实还有一个问题。即IMageLIstView中第一个方法中的 imageView.tag = 1000 + i，这个代表了什么我其实不太明白诶。另外在导入pods后，Frameworks中的.a文件显示红色，我在网上查到好多方法试过了都没有作用。如果您方便的话可以解答一下吗？我这边因为刚刚开始学习，可能问题比较繁琐，谢谢您啦~
> 
> hi.....，libPods-MomentKit.a显示红色并不影响运行的。理论上执行完pod install，模拟器就可以运行成功，可以看到页面啦。如果没有运行成功，还得具体看报错信息。 imageView.tag = 1000 + i，就是设置tag，为了防止tag从0开始，因为[self viewWithTag:0]取得是self。

是的哦~确实不影响运行的。可能我之前表达的不太清楚。我的困惑在于那个tag是什么（简单点说就是中文怎么翻译，我觉得它像个缩写），我不能理解它起到的作用。

**Comment by ChellyLau** [comment]
> > > > > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> > > > 
> > > > 
> > > > sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。
> > > 
> > > 
> > > 啊！谢谢关注到我的留言，其实确实还有一个问题。即IMageLIstView中第一个方法中的 imageView.tag = 1000 + i，这个代表了什么我其实不太明白诶。另外在导入pods后，Frameworks中的.a文件显示红色，我在网上查到好多方法试过了都没有作用。如果您方便的话可以解答一下吗？我这边因为刚刚开始学习，可能问题比较繁琐，谢谢您啦~
> > 
> > 
> > hi.....，libPods-MomentKit.a显示红色并不影响运行的。理论上执行完pod install，模拟器就可以运行成功，可以看到页面啦。如果没有运行成功，还得具体看报错信息。 imageView.tag = 1000 + i，就是设置tag，为了防止tag从0开始，因为[self viewWithTag:0]取得是self。
> 
> 是的哦~确实不影响运行的。可能我之前表达的不太清楚。我的困惑在于那个tag是什么（简单点说就是中文怎么翻译，我觉得它像个缩写），我不能理解它起到的作用。

简单的讲，tag是视图的标签，用于方便通过父视图获取子视图，例如：UIView *subView = [parentView viewWithTag:tag]。

**Comment by slz759** [comment]
> > > > > > 那天我改了一下代码让朋友圈预览图片正好每行三张铺满，今天死活找不到那一行代码了。麻烦指教一下谢谢！！！
> > > > > 
> > > > > 
> > > > > sorry啊，不小心关掉了你的问题。。后面再有什么问题，还请issue我。
> > > > 
> > > > 
> > > > 啊！谢谢关注到我的留言，其实确实还有一个问题。即IMageLIstView中第一个方法中的 imageView.tag = 1000 + i，这个代表了什么我其实不太明白诶。另外在导入pods后，Frameworks中的.a文件显示红色，我在网上查到好多方法试过了都没有作用。如果您方便的话可以解答一下吗？我这边因为刚刚开始学习，可能问题比较繁琐，谢谢您啦~
> > > 
> > > 
> > > hi.....，libPods-MomentKit.a显示红色并不影响运行的。理论上执行完pod install，模拟器就可以运行成功，可以看到页面啦。如果没有运行成功，还得具体看报错信息。 imageView.tag = 1000 + i，就是设置tag，为了防止tag从0开始，因为[self viewWithTag:0]取得是self。
> > 
> > 
> > 是的哦~确实不影响运行的。可能我之前表达的不太清楚。我的困惑在于那个tag是什么（简单点说就是中文怎么翻译，我觉得它像个缩写），我不能理解它起到的作用。
> 
> 简单的讲，tag是视图的标签，用于方便通过父视图获取子视图，例如：UIView *subView = [parentView viewWithTag:tag]。

好的，我去理解下，谢谢您！
