### ISSUE TITLE
对点赞 做操作  数据更新完 reloadData完 界面就会跳一下 

### ISSUE THREAD

**Issue by xrrrrr** [ChellyLau/MomentKit#6]
对点赞 做操作  数据更新完 reloadData完 界面就会跳一下 ,  作者有注意到嘛

**Comment by CheeryLau** [comment]
加上这一句：tableView.estimatedRowHeight = 0;

**Comment by ChellyLau** [comment]
> 对点赞 做操作 数据更新完 reloadData完 界面就会跳一下 , 作者有注意到嘛

新版本已修复，请使用最新code。
