### ISSUE TITLE
如果有以下功能就好了

### ISSUE THREAD

**Issue by xiongjw** [ChellyLau/MomentKit#7]
1、点赞列表的配置包含id,点击时可以跳转个人详情
2、点击评论内容,起键盘,定位到此评论位置, 点击评论或者回复人,同样能跟1一样,包含id进入个人详情
3、正文内容可以复制

**Comment by ChellyLau** [comment]
> 1、点赞列表的配置包含id,点击时可以跳转个人详情
> 2、点击评论内容,起键盘,定位到此评论位置, 点击评论或者回复人,同样能跟1一样,包含id进入个人详情
> 3、正文内容可以复制

不好意思，刚看到。哈哈哈......满足你，新版本功能已覆盖，请使用最新code。
