### ISSUE TITLE
具体怎么使用？

### ISSUE THREAD

**Issue by QiaoLansheng** [ChellyLau/MomentKit#8]
您好这个具体怎么使用？能否模拟一下做出来假的评论和回复操作啊？

**Comment by ChellyLau** [comment]
好的，后期更新一下。

**Comment by ChellyLau** [comment]
> 您好这个具体怎么使用？能否模拟一下做出来假的评论和回复操作啊？

新版本已覆盖多种功能，请使用最新code。
