### ISSUE TITLE
Swift版本的也支持一下？

### ISSUE THREAD

**Issue by ruitobe** [ChellyLau/MomentKit#9]
是否有swift 版本支持？

**Comment by ChellyLau** [comment]
暂不支持，我想着有时间先把功能丰富一下。

**Comment by ChellyLau** [comment]
> 是否有swift 版本支持？



> 是否有swift 版本支持？

暂不支持，还请见谅。

**Comment by ChellyLau** [comment]
> 是否有swift 版本支持？

暂不支持，还请见谅。
